# Generated by Django 4.0.2 on 2022-05-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_ratefact_productratefact_reviewratefact'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agreement',
            field=models.FileField(default=1, upload_to='agreements'),
            preserve_default=False,
        ),
    ]
