# Generated by Django 4.0.2 on 2022-03-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20220324_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristic',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
