# Generated by Django 4.0.2 on 2022-05-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_application_agreement'),
        ('main', '0020_alter_productcharacteristic_product'),
    ]

    operations = [
    ]
