# Generated by Django 4.0.2 on 2022-05-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_merge_20220510_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparingreview',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
